#!/bin/bash

cfssl genkey -initca root-csr.json | cfssljson -bare ca
cfssl gencert -ca ca.pem -ca-key ca-key.pem server-csr.json | cfssljson -bare server
cfssl gencert -ca ca.pem -ca-key ca-key.pem client-csr.json | cfssljson -bare client

rm -f ca-key.pem ca.csr server.csr client.csr
